### ISSUE TITLE
dropwizard-sentry does not work with dropwizard version of 3.0.3

### ISSUE THREAD

**Issue by kouros51** [dhatim/dropwizard-sentry#126]
Here the exception we got:
```bash
io.dropwizard.configuration.ConfigurationParsingException: configuration.yml has an error:
  * Failed to parse configuration at: logging.appenders.[1]; Could not resolve type id 'sentry' as a subtype of `io.dropwizard.logging.common.AppenderFactory<ch.qos.logback.classic.spi.ILoggingEvent>`: known type ids = [console, file, syslog, tcp, tls, udp] (for POJO property 'appenders')
 at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: com.example.Configuration["logging"]->io.dropwizard.logging.common.DefaultLoggingFactory["appenders"]->java.util.ArrayList[1])
	at io.dropwizard.configuration.ConfigurationParsingException$Builder.build(ConfigurationParsingException.java:277)
	at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:177)
	at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:94)
	at io.dropwizard.core.cli.ConfiguredCommand.parseConfiguration(ConfiguredCommand.java:139)
	at io.dropwizard.core.cli.ConfiguredCommand.run(ConfiguredCommand.java:85)
.....
Caused by: com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Could not resolve type id 'sentry' as a subtype of `io.dropwizard.logging.common.AppenderFactory<ch.qos.logback.classic.spi.ILoggingEvent>`: known type ids = [console, file, syslog, tcp, tls, udp] (for POJO property 'appenders')
 at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: com.example.Configuration["logging"]->io.dropwizard.logging.common.DefaultLoggingFactory["appenders"]->java.util.ArrayList[1])
	at com.fasterxml.jackson.databind.exc.InvalidTypeIdException.from(InvalidTypeIdException.java:43)
	at com.fasterxml.jackson.databind.DeserializationContext.invalidTypeIdException(DeserializationContext.java:2084)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownTypeId(DeserializationContext.java:1575)
	at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._handleUnknownTypeId(TypeDeserializerBase.java:298)
	at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._findDeserializer(TypeDeserializerBase.java:165)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:151)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:136)
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:263)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:361)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
```

**Comment by DevinOM** [comment]
Any luck with this? Having a similar issue with my app that's using DW 3.0.2
